# Generated by Django 3.1.1 on 2023-05-11 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Catagory', '0002_auto_20230510_1520'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
    ]
